/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register-company`; params?: Router.UnknownInputParams; } | { pathname: `/register-driver`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(company)'}/create-job` | `/create-job`; params?: Router.UnknownInputParams; } | { pathname: `${'/(company)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(company)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(driver)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(driver)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(driver)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/candidates/[jobId]`, params: Router.UnknownInputParams & { jobId: string | number; } } | { pathname: `/driver-view/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/evaluate/[driverId]`, params: Router.UnknownInputParams & { driverId: string | number; } } | { pathname: `/job/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register-company`; params?: Router.UnknownOutputParams; } | { pathname: `/register-driver`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(company)'}/create-job` | `/create-job`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(company)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(company)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(driver)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(driver)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(driver)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/candidates/[jobId]`, params: Router.UnknownOutputParams & { jobId: string; } } | { pathname: `/driver-view/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/evaluate/[driverId]`, params: Router.UnknownOutputParams & { driverId: string; } } | { pathname: `/job/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register-company${`?${string}` | `#${string}` | ''}` | `/register-driver${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(company)'}/create-job${`?${string}` | `#${string}` | ''}` | `/create-job${`?${string}` | `#${string}` | ''}` | `${'/(company)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(company)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(driver)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(driver)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(driver)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register-company`; params?: Router.UnknownInputParams; } | { pathname: `/register-driver`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(company)'}/create-job` | `/create-job`; params?: Router.UnknownInputParams; } | { pathname: `${'/(company)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(company)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(driver)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(driver)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(driver)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | `/candidates/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/driver-view/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/evaluate/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/job/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/candidates/[jobId]`, params: Router.UnknownInputParams & { jobId: string | number; } } | { pathname: `/driver-view/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/evaluate/[driverId]`, params: Router.UnknownInputParams & { driverId: string | number; } } | { pathname: `/job/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
